/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MapCode: typeof import('./src/components/MapConfigurator/MapCode.vue')['default']
    MapConfigurator: typeof import('./src/components/MapConfigurator/MapConfigurator.vue')['default']
    MapSettings: typeof import('./src/components/MapConfigurator/MapSettings.vue')['default']
  }
}
